# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-fILTchoeKQZH4ELyYj6MeoCsk9wZpoo
"""

2age=12
print(2age)

age=12
print(age)

age1=12
print(age1)

python=8
print(python)

emp_id=500
print(emp_id)

emp@id=500
print(emp@id)

_emp_id=500
print(_emp_id)

a=2
b=3
print(a+b)

a=2
b=3
print(a-b)

a=2
b=3
print(a*b)

a=2
b=3
print(a/b)

a=2
b=3
print(a%b)

a=2
b=3
print(a**b)

a=2
b=3
print(a^b)

a=7+5*(2**6)
print(a)

a=10
b=9
a+=b
print(a)

a=2
b=3
b+=a
print(a)

x=19
y=76
print(x==y)

a=2
b=2
print(a==b)

a=8
b=9
print(a!=b)

a=89
b=97
print(a>b)

a=2
b=3
print(a<b)

a=89
b=97
print(a>=b)

a=100
b=97
print(a>=b)

a=89
b=97
print(a<=b)

a=int(input('enter the num'))
b=int(input("enter the num"))
print(a>=b)

age=2
if age>18:
 print("eligible for vote")
else:
  print("not eligible")

age=77
if age>18:
 print("eligible for vote")
else:
  print("not eligible")

age=int(input("enter the age"))
if age>18:
 print("eligible for vote")
else:
  print("not eligible")

mark=95
if mark>50:
 print("pass")
 print("congratulations")
else:
  print("fail")

mark=int(input("enter the marks:"))
if mark>50:
 print("pass")
 print("congratulations")
else:
  print("fail")

mark=float(input("enter the marks:"))
if mark>50:
 print("pass")
 print("congratulations")
else:
  print("fail")

mark=int(input("enter the marks:"))
if mark>50:
 print("pass")
 print("congratulations")
if mark>75:
  print("grade A")
if mark>85:
  print("grade A+")

mark=int(input("enter the marks:"))
if mark>50:
 print("pass")

elif mark<50:
  print("fail")
elif mark>85:
  print("grade A+")

a=int(input('enter the num:'))
b=int(input("enter the num:"))
print(a<b) and (a!=b)

a=int(input('enter the num:'))
b=int(input("enter the num:"))
print(a>1b) or (a!=b)

a=int(input('enter the num:'))
b=int(input("enter the num:"))
print(not(a<b))

is_logged_in=True
if not is_logged_in:
  print("please log in")
else:
  print("welcome")

a=int(input('enter the num:'))

print(type(a))

a=float(input('enter the num:'))
print(type(a))

a=float(input('enter the num:'))
b=float(input("enter the num:"))
print(a+b)

a=int(input('enter the num:'))
b=int(input("enter the num:"))
print(a+b)

c1=complex(3,2)
c2=complex(4,5)
print(c1)
print(c2)
print(c1.real)
print(c2.imag)

a=10
b=4
c=a&b
print(c)

a=10
b=4
c=a|b
print(c)

a=10
b=4
c=a^b
print(c)

a=6
c=a<<1
print(c)

a=6
c=a>>8
print(c)

a="h"
b="k"
print(a+b)

a="keerthi"
print(a[0])

a="keerthi"
print(a[1])

a="keerthi"
print(a[-1])

a="keerthi"
print(a[0:3])

a="keerthi"
print(a[1:3])

a="123456789"
print(a[0:10:5])

a="data"
b="science"
print(a+""+b)

word="hi"
print((word+" ")* 6)

word="hi"
print(word* 6)

word="hi"
print((word+"\n")* 6)

x="python"
print(len(x))

x=input("enter the str:")
print(len(x))

age="56"
print(type(age))

age=int("56")
print(type(age))

age=56
print(type(age))

age=str(56)
print(type(age))

s="SPIDERMAN BRAND NEW DAY"
print(s.find("W"))

s="SPIDERMAN BRAND NEW DAY"
print(s.rfind("Y"))
print(s.count("A"))
print(len(s))
print(s.startswith("A"))
print(s.endswith("Y"))
print(s.lower())
print(s.upper())
print(s.title())

text="i love java"
print(text.replace("java","python"))

text="i love java"
print(text.replace("java","python"))
print(text)

text="i love java"
text=text.replace("java","python")
print(text)

text="i love java"
print(text.split())
print(text.split("v"))
print(text.split("a",3))

name="keerthi"
dream="doctor"
print(f"my name is {name} and her dream is {dream}")

s="aladdin"
s[0]="h"

s="aladdin"
print("h"+s[1:])

a="data"
print("d"in a)

a="data"
print("d"not in a)

a=" AVERAGE mark "
print(a.strip())

a=" AVERAGE mark "
b=a.replace("mark","score")
print(a.strip())
print(b)

a=[]
print(type(a))

a=[1,3,"keeert",4,5]
print((a))
print(a[2])
print(a[0:3])
print(a[-1])
print(a[0:3:4])

a=[1,3,"keeert",4,5]
b=[5,6,7]
print(a+b)

b=[5,6,7]
b.append("7")
b.insert(1,100)
b.remove(7)
b.pop()
b.pop(2)
print(b)